name: Verify examples
on: [push, pull_request]

jobs:
  find_examples:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-dirs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Gather directories inside examples
        id: find-dirs
        run: |
          cd examples
          echo "matrix={\"dir\":[$(for dir in $(echo */); do echo -n \"${dir%?}\",; done)]}" >> $GITHUB_OUTPUT
  build_latex:
    needs: find_examples
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.find_examples.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Check that LaTeX example compiles
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: examples/${{ matrix.dir }}
          pre_compile: |
            cp -r ../../* . || true
          root_file: main.tex
          latexmk_shell_escape: true
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Log - ${{ matrix.dir }}
          path: examples/${{ matrix.dir }}/main.log
